name: web_socket_manager
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

# Add regular dependencies here.
dependencies:
  web_socket_channel: ^3.0.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
